### PR TITLE
console

### PR DESCRIPTION
**Pull request by shwetatalreja**

### CODE REVIEW

**Comment by vivekjha4u2** [comment]
Hi Shweta, i would like to apprreciate the efforts you are putting into this project :D

**Comment by shwetatalreja** [comment]
Can you please tell what have i done in your project..

**Comment by vivekjha4u2** [comment]
given your time & that matters

**Comment by vivekjha4u2** [comment]
Kaisa laga mera jawab 😎😎🤣🤣

**Comment by shwetatalreja** [comment]
thanks for the bejjati vivek jha

**Review by vivekjha4u2 — APPROVED** [review]

**Pull request merged**
